// <auto-generated />
using System;
using MC.CommerceService.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MC.CommerceService.API.Data.Migrations
{
    [DbContext(typeof(CommerceDBContext))]
    [Migration("20240914032531_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MC.CommerceService.API.Data.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222221"),
                            CategoryName = "Electronics",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 8, DateTimeKind.Unspecified).AddTicks(9650), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 8, DateTimeKind.Unspecified).AddTicks(9652), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CategoryName = "Books",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 8, DateTimeKind.Unspecified).AddTicks(9654), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 8, DateTimeKind.Unspecified).AddTicks(9655), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222223"),
                            CategoryName = "Clothing",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 8, DateTimeKind.Unspecified).AddTicks(9657), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 8, DateTimeKind.Unspecified).AddTicks(9658), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222224"),
                            CategoryName = "Home & Kitchen",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 8, DateTimeKind.Unspecified).AddTicks(9660), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 8, DateTimeKind.Unspecified).AddTicks(9661), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222225"),
                            CategoryName = "Sports",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 8, DateTimeKind.Unspecified).AddTicks(9663), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 8, DateTimeKind.Unspecified).AddTicks(9663), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        });
                });

            modelBuilder.Entity("MC.CommerceService.API.Data.Models.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CustomerId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 9, DateTimeKind.Unspecified).AddTicks(4833), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 9, DateTimeKind.Unspecified).AddTicks(4834), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Phone = "123-456-7890"
                        },
                        new
                        {
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 9, DateTimeKind.Unspecified).AddTicks(4838), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 9, DateTimeKind.Unspecified).AddTicks(4838), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Phone = "234-567-8901"
                        },
                        new
                        {
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 9, DateTimeKind.Unspecified).AddTicks(4847), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            Email = "michael.johnson@example.com",
                            FirstName = "Michael",
                            LastName = "Johnson",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 9, DateTimeKind.Unspecified).AddTicks(4848), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Phone = "345-678-9012"
                        },
                        new
                        {
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 9, DateTimeKind.Unspecified).AddTicks(4851), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            Email = "emily.williams@example.com",
                            FirstName = "Emily",
                            LastName = "Williams",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 9, DateTimeKind.Unspecified).AddTicks(4851), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Phone = "456-789-0123"
                        },
                        new
                        {
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 9, DateTimeKind.Unspecified).AddTicks(4853), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            Email = "chris.brown@example.com",
                            FirstName = "Chris",
                            LastName = "Brown",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 9, DateTimeKind.Unspecified).AddTicks(4854), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Phone = "567-890-1234"
                        });
                });

            modelBuilder.Entity("MC.CommerceService.API.Data.Models.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = new Guid("33333333-3333-3333-3333-333333333331"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 10, DateTimeKind.Unspecified).AddTicks(786), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000001"),
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 10, DateTimeKind.Unspecified).AddTicks(787), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            OrderDate = new DateTime(2024, 9, 14, 3, 25, 31, 10, DateTimeKind.Utc).AddTicks(782),
                            TotalAmount = 500m
                        },
                        new
                        {
                            OrderId = new Guid("33333333-3333-3333-3333-333333333332"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 10, DateTimeKind.Unspecified).AddTicks(790), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000002"),
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 10, DateTimeKind.Unspecified).AddTicks(791), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            OrderDate = new DateTime(2024, 9, 14, 3, 25, 31, 10, DateTimeKind.Utc).AddTicks(790),
                            TotalAmount = 1000m
                        },
                        new
                        {
                            OrderId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 10, DateTimeKind.Unspecified).AddTicks(794), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000003"),
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 10, DateTimeKind.Unspecified).AddTicks(794), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            OrderDate = new DateTime(2024, 9, 14, 3, 25, 31, 10, DateTimeKind.Utc).AddTicks(793),
                            TotalAmount = 750m
                        },
                        new
                        {
                            OrderId = new Guid("33333333-3333-3333-3333-333333333334"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 10, DateTimeKind.Unspecified).AddTicks(797), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000004"),
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 10, DateTimeKind.Unspecified).AddTicks(797), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            OrderDate = new DateTime(2024, 9, 14, 3, 25, 31, 10, DateTimeKind.Utc).AddTicks(796),
                            TotalAmount = 900m
                        },
                        new
                        {
                            OrderId = new Guid("33333333-3333-3333-3333-333333333335"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 10, DateTimeKind.Unspecified).AddTicks(800), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000005"),
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 10, DateTimeKind.Unspecified).AddTicks(801), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            OrderDate = new DateTime(2024, 9, 14, 3, 25, 31, 10, DateTimeKind.Utc).AddTicks(800),
                            TotalAmount = 1200m
                        });
                });

            modelBuilder.Entity("MC.CommerceService.API.Data.Models.OrderProduct", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts");

                    b.HasData(
                        new
                        {
                            OrderId = new Guid("33333333-3333-3333-3333-333333333331"),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(278), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(279), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = new Guid("33333333-3333-3333-3333-333333333331"),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111112"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(336), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(337), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = new Guid("33333333-3333-3333-3333-333333333331"),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111113"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(338), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(339), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = new Guid("33333333-3333-3333-3333-333333333332"),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111114"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(340), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(340), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = new Guid("33333333-3333-3333-3333-333333333332"),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111115"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(341), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(342), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = new Guid("33333333-3333-3333-3333-333333333332"),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111116"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(343), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(343), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111117"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(344), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(345), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111118"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(346), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(346), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = new Guid("33333333-3333-3333-3333-333333333334"),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111119"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(347), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(348), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = new Guid("33333333-3333-3333-3333-333333333334"),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111120"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(349), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(349), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = new Guid("33333333-3333-3333-3333-333333333334"),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111121"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(350), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(350), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = new Guid("33333333-3333-3333-3333-333333333335"),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111122"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(352), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(352), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = new Guid("33333333-3333-3333-3333-333333333335"),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111123"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(353), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(354), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = new Guid("33333333-3333-3333-3333-333333333335"),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111124"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(355), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(355), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = new Guid("33333333-3333-3333-3333-333333333335"),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111125"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(356), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(357), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("MC.CommerceService.API.Data.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "P001",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(4029), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            Description = "A powerful laptop",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(4030), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Price = 1000m,
                            Stock = 50,
                            Title = "Laptop"
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Code = "P002",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(4034), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            Description = "A modern smartphone",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(4035), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Price = 800m,
                            Stock = 30,
                            Title = "Smartphone"
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111113"),
                            Code = "P003",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(4038), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            Description = "A versatile tablet",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(4039), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Price = 500m,
                            Stock = 20,
                            Title = "Tablet"
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111114"),
                            Code = "P004",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(4041), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            Description = "Noise-canceling headphones",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(4042), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Price = 200m,
                            Stock = 100,
                            Title = "Headphones"
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111115"),
                            Code = "P005",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(4045), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            Description = "A stylish smartwatch",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(4045), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Price = 250m,
                            Stock = 60,
                            Title = "Smartwatch"
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111116"),
                            Code = "P006",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(4048), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            Description = "A 24-inch monitor",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(4049), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Price = 300m,
                            Stock = 40,
                            Title = "Monitor"
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111117"),
                            Code = "P007",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(4052), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            Description = "Mechanical keyboard",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(4052), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Price = 100m,
                            Stock = 70,
                            Title = "Keyboard"
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111118"),
                            Code = "P008",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(4055), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            Description = "Wireless mouse",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(4055), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Price = 50m,
                            Stock = 80,
                            Title = "Mouse"
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111119"),
                            Code = "P009",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(4061), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            Description = "Ergonomic office chair",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(4062), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Price = 150m,
                            Stock = 25,
                            Title = "Chair"
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111120"),
                            Code = "P010",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(4065), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            Description = "Adjustable standing desk",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(4065), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Price = 500m,
                            Stock = 20,
                            Title = "Desk"
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111121"),
                            Code = "P011",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(4068), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            Description = "Wireless printer",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(4069), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Price = 200m,
                            Stock = 15,
                            Title = "Printer"
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111122"),
                            Code = "P012",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(4071), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            Description = "Document scanner",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(4072), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Price = 150m,
                            Stock = 30,
                            Title = "Scanner"
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111123"),
                            Code = "P013",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(4074), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            Description = "HD webcam",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(4075), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Price = 80m,
                            Stock = 50,
                            Title = "Webcam"
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111124"),
                            Code = "P014",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(4077), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            Description = "Wireless router",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(4078), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Price = 120m,
                            Stock = 45,
                            Title = "Router"
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111125"),
                            Code = "P015",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(4080), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            Description = "1TB external hard drive",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(4081), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = "",
                            Price = 90m,
                            Stock = 100,
                            Title = "External Hard Drive"
                        });
                });

            modelBuilder.Entity("MC.CommerceService.API.Data.Models.ProductCategory", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("ProductCategory");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222221"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9970), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9971), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9972), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9973), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111112"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222221"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9974), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9974), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111112"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222223"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9975), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9976), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111113"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9977), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9978), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111113"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222224"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9979), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9979), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111114"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222223"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9980), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9981), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111114"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222225"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9982), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9982), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111115"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222221"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9983), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9983), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111115"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222224"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9985), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9985), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111116"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9986), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9987), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111116"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222225"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9987), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9988), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111117"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222223"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9989), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9989), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111117"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222221"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9991), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9991), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111118"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222225"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9992), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9993), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111118"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9993), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9994), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111119"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222224"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9995), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9995), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111119"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222221"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9996), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9996), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111120"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9997), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9998), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111120"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222223"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9999), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 11, DateTimeKind.Unspecified).AddTicks(9999), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111121"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222225"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(1), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111121"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222224"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(1), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(2), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111122"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222221"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(3), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(4), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111122"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222225"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(5), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(5), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111123"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(6), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(6), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111123"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222224"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(7), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(8), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111124"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222223"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(9), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(9), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111124"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222225"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(12), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(13), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111125"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222221"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(14), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(14), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111125"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222223"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(15), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(16), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222223"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(16), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(17), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111112"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222224"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(18), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(18), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111113"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222225"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(19), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(20), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111114"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222221"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(21), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(21), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        },
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111115"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(22), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "",
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 14, 3, 25, 31, 12, DateTimeKind.Unspecified).AddTicks(22), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdatedBy = ""
                        });
                });

            modelBuilder.Entity("MC.CommerceService.API.Data.Models.Order", b =>
                {
                    b.HasOne("MC.CommerceService.API.Data.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MC.CommerceService.API.Data.Models.OrderProduct", b =>
                {
                    b.HasOne("MC.CommerceService.API.Data.Models.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MC.CommerceService.API.Data.Models.Product", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MC.CommerceService.API.Data.Models.ProductCategory", b =>
                {
                    b.HasOne("MC.CommerceService.API.Data.Models.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MC.CommerceService.API.Data.Models.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MC.CommerceService.API.Data.Models.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("MC.CommerceService.API.Data.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MC.CommerceService.API.Data.Models.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("MC.CommerceService.API.Data.Models.Product", b =>
                {
                    b.Navigation("OrderProducts");

                    b.Navigation("ProductCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
